repos:
  - repo: local
    hooks:
      - id: check
        name: check
        language: system
        entry: cargo check --all-targets
        pass_filenames: false
        always_run: true

      - id: rustfmt
        name: rustfmt
        language: system
        entry: cargo fmt --check
        pass_filenames: false
        always_run: true

      - id: clippy
        name: clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        pass_filenames: false
        always_run: true

      - id: tests
        name: tests
        entry: cargo make tests
        language: system
        pass_filenames: false
        always_run: true

      - id: build
        name: build
        entry: cargo make build
        language: system
        pass_filenames: false
        always_run: true

      - id: examples
        name: examples
        entry: cargo make examples
        language: system
        pass_filenames: false
        always_run: true

      - id: doc
        name: doc
        entry: cargo doc
        language: system
        pass_filenames: false
        always_run: true

      - id: bench
        name: bench
        entry: cargo bench
        language: system
        pass_filenames: false
        always_run: true
