repos:
  - repo: local
    hooks:
      - id: check
        name: check
        language: system
        entry: cargo check --all-targets
        pass_filenames: false
        always_run: true

      - id: rustfmt
        name: rustfmt
        language: system
        entry: cargo fmt --check
        pass_filenames: false
        always_run: true

      - id: clippy
        name: clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        pass_filenames: false
        always_run: true

      - id: test
        name: test
        entry: cargo test
        language: system
        pass_filenames: false
        always_run: true

      - id: build
        name: build
        entry: cargo make build-wasm32
        language: system
        pass_filenames: false
        always_run: true

      - id: bench
        name: bench
        entry: cargo bench
        language: system
        pass_filenames: false
        always_run: true
