[package]
name = "microgemm"
version = "0.1.0"
edition = "2021"
rust-version = "1.65.0"
authors = ["cospectrum"]

description = "General matrix multiplication with custom configuration in Rust"
license = "MIT OR Apache-2.0"

repository = "https://github.com/cospectrum/microgemm"
readme = "README.md"
categories = ["science", "mathematics", "no-std", "no-std::no-alloc"]
keywords = ["matrix", "linear-algebra"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generic-array = { version = "1.0.0", default-features = false }
num-traits = { version = "0.2.17", default-features = false }

[dev-dependencies]
approx = "0.5.1"
criterion = "0.5.1"
rand = "0.8.5"

[[bench]]
name = "gemm_f32"
harness = false
