[tasks.comparison]
command = "cargo"
args = ["test", "--release", "--test", "comparison", "--", "--ignored", "--nocapture"]

[tasks.bench]
command = "cargo"
args = ["bench"]
dependencies = ["comparison"]

[tasks.sanitize-neon]
toolchain = "nightly"
env = { "RUSTFLAGS" = "-Z sanitizer=address" }
command = "cargo"
args = ["test", "neon", "--target", "aarch64-apple-darwin"]

[tasks.sans]
env = { "RUSTFLAGS" = {unset = true} }
dependencies = ["sanitize-neon"]
