name: wasm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: check
        run: RUSTFLAGS="-D warnings" cargo check --target wasm32-unknown-unknown
      - name: check-simd128
        run: RUSTFLAGS="-D warnings -C target-feature=+simd128" cargo check --target wasm32-unknown-unknown

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: RUSTFLAGS="-D warnings -C target-feature=+simd128" wasm-pack test --headless --chrome --release
      - run: RUSTFLAGS="-D warnings -C target-feature=+simd128" wasm-pack test --headless --firefox --release
